# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_trajectory_controller
    - gripper_action_controller

  arm_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
    action_ns: follow_joint_trajectory
    default: true
  gripper_action_controller:
    type: GripperCommand
    joints:
      - joint_4
    action_ns: gripper_cmd
    default: true