controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  ros__parameters: {}

arm_trajectory_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  ros__parameters:
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_action_controller:
  type: joint_trajectory_controller/GripperActionController
  ros__parameters:
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    allow_goal_in_tolerance: true
    goal_tolerance: 0.01
    joint: joint_4
    max_effort: 100.0
    stall_timeout: 3.0
    stall_velocity_threshold: 0.001
